name: build kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Set Timezone
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex perl \
            libssl-dev libelf-dev libfl-dev libncursesw5-dev \
            aria2 curl wget git ccache python3 python3-pip \
            zip unzip tar gzip bzip2 lz4 zstd clang llvm \
            device-tree-compiler libarchive-tools ca-certificates

      - name: Build Kernel
        run: |
          chmod +x build.sh
          ./build.sh --ksu

      - name: Find ZIP
        id: find_zip
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
          echo "Found ZIP: $ZIP_FILE"

      - name: Upload Kernel ZIP
        uses: actions/upload-artifact@v7
        with:
          name: kernel-artifact
          path: ${{ env.ZIP_FILE }}
